// backend/controllers/aiDiscoveryController.js
import express from 'express';
import aiDiscoveryService from '../services/aiDiscoveryService.js';
import Shop from '../db/Shop.js';

const router = express.Router();

/**
 * Helper to get shop session
 */
async function getShopSession(shopParam) {
  const shopDoc = await Shop.findOne({ shop: shopParam });
  if (!shopDoc || !shopDoc.accessToken) {
    throw new Error('Shop not found or not authenticated');
  }
  
  return {
    shop: shopDoc.shop,
    accessToken: shopDoc.accessToken,
    // Create session object for shopifyAdmin
    session: {
      shop: shopDoc.shop,
      accessToken: shopDoc.accessToken
    }
  };
}

/**
 * GET /api/ai-discovery/settings
 */
router.get('/ai-discovery/settings', async (req, res) => {
  try {
    const shop = req.query.shop;
    if (!shop) {
      return res.status(400).json({ error: 'Missing shop parameter' });
    }
    
    const { session } = await getShopSession(shop);
    
    // Get current plan
    const planResponse = await fetch(`${process.env.APP_URL}/plans/me?shop=${shop}`);
    const planData = await planResponse.json();
    const rawPlan = planData.plan || 'starter';
    const normalizedPlan = rawPlan.toLowerCase().replace(/\s+/g, '_');
    
    // Get saved settings
    const savedSettings = await aiDiscoveryService.getSettings(shop, session);
    
    // Get default structure for the plan
    const defaultSettings = aiDiscoveryService.getDefaultSettings(normalizedPlan);
    
    // IMPORTANT: Don't merge features from defaultSettings if there are no saved settings
    const mergedSettings = {
      plan: rawPlan,
      availableBots: defaultSettings.availableBots,
      bots: savedSettings.bots || defaultSettings.bots,
      features: savedSettings.features || defaultSettings.features, // Will be all false from default
      updatedAt: savedSettings.updatedAt || new Date().toISOString()
    };
    
    res.json(mergedSettings);
  } catch (error) {
    console.error('Failed to get AI Discovery settings:', error);
    res.status(500).json({ error: error.message });
  }
});

/**
 * POST /api/ai-discovery/settings
 */
router.post('/ai-discovery/settings', async (req, res) => {
  try {
    const { shop, bots, features } = req.body;
    
    if (!shop || !bots || !features) {
      return res.status(400).json({ error: 'Missing required fields' });
    }
    
    const { session } = await getShopSession(shop);
    
    const settings = { bots, features };
    await aiDiscoveryService.updateSettings(shop, session, settings);
    
    res.json({ success: true, settings });
  } catch (error) {
    console.error('Failed to update AI Discovery settings:', error);
    res.status(500).json({ error: error.message });
  }
});

/**
 * GET /api/ai-discovery/robots-txt
 */
router.get('/ai-discovery/robots-txt', async (req, res) => {
  try {
    const shop = req.query.shop;
    if (!shop) {
      return res.status(400).json({ error: 'Missing shop parameter' });
    }
    
    const { session } = await getShopSession(shop);
    const settings = await aiDiscoveryService.getSettings(shop, session);
    const robotsTxt = aiDiscoveryService.generateRobotsTxt(settings, shop);
    
    res.type('text/plain').send(robotsTxt);
  } catch (error) {
    console.error('Failed to generate robots.txt:', error);
    res.status(500).json({ error: error.message });
  }
});

/**
 * POST /api/ai-discovery/apply-robots
 */
router.post('/ai-discovery/apply-robots', async (req, res) => {
  console.log('[ROBOTS] Starting apply-robots endpoint');
  
  try {
    const { shop } = req.body;
    const { session, accessToken } = await getShopSession(shop);
    
    // Check plan
    const planResponse = await fetch(`${process.env.APP_URL}/plans/me?shop=${shop}`);
    const planData = await planResponse.json();
    const normalizedPlan = (planData.plan || 'starter').toLowerCase().replace(/\s+/g, '_');
    
    if (!['growth', 'growth_extra', 'enterprise'].includes(normalizedPlan)) {
      return res.status(403).json({ 
        error: 'Automatic robots.txt requires Growth plan or higher' 
      });
    }
    
    // Get settings and generate robots.txt
    const settings = await aiDiscoveryService.getSettings(shop, session);
    const robotsTxt = aiDiscoveryService.generateRobotsTxt(settings, shop);
    
    const robotsTxtContent = `{% comment %}
AI Discovery - Auto-generated by AI SEO 2.0
Last updated: ${new Date().toISOString()}
{% endcomment %}
${robotsTxt}

{% comment %} Include any existing robots.txt content {% endcomment %}
`;
    
    // Get PUBLISHED theme (not test theme!)
    const themesResponse = await fetch(
      `https://${shop}/admin/api/2024-07/themes.json?role=main`,
      {
        headers: {
          'X-Shopify-Access-Token': accessToken,
          'Content-Type': 'application/json'
        }
      }
    );
    
    const themesData = await themesResponse.json();
    const publishedTheme = themesData.themes?.[0]; // role=main returns only published
    
    if (!publishedTheme) {
      return res.status(404).json({ error: 'No published theme found' });
    }
    
    console.log('[ROBOTS] Published theme:', publishedTheme.name, publishedTheme.id);
    
    // Attempt 1: Direct creation in templates/
    let assetResponse = await fetch(
      `https://${shop}/admin/api/2024-07/themes/${publishedTheme.id}/assets.json`,
      {
        method: 'PUT',
        headers: {
          'X-Shopify-Access-Token': accessToken,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          asset: {
            key: 'templates/robots.txt.liquid',
            value: robotsTxtContent
          }
        })
      }
    );
    
    // If failed in templates/, try root
    if (!assetResponse.ok) {
      console.log('[ROBOTS] Failed in templates/, trying root...');
      
      assetResponse = await fetch(
        `https://${shop}/admin/api/2024-07/themes/${publishedTheme.id}/assets.json`,
        {
          method: 'PUT',
          headers: {
            'X-Shopify-Access-Token': accessToken,
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            asset: {
              key: 'robots.txt',  // Without .liquid
              value: robotsTxtContent
            }
          })
        }
      );
    }
    
    if (!assetResponse.ok) {
      // Last attempt - layout/robots.liquid
      console.log('[ROBOTS] Failed in root, trying layout/...');
      
      assetResponse = await fetch(
        `https://${shop}/admin/api/2024-07/themes/${publishedTheme.id}/assets.json`,
        {
          method: 'PUT',
          headers: {
            'X-Shopify-Access-Token': accessToken,
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            asset: {
              key: 'layout/robots.liquid',
              value: robotsTxtContent
            }
          })
        }
      );
    }
    
    if (assetResponse.ok) {
      const result = await assetResponse.json();
      res.json({ 
        success: true, 
        message: `robots.txt applied to ${publishedTheme.name}`,
        location: result.asset?.key
      });
    } else {
      throw new Error('Could not create robots file in any location');
    }
    
  } catch (error) {
    console.error('[ROBOTS] Error:', error);
    res.status(500).json({ error: error.message });
  }
});

/**
 * DELETE /api/ai-discovery/settings - Reset settings to defaults
 */
router.delete('/ai-discovery/settings', async (req, res) => {
  try {
    const shop = req.query.shop;
    if (!shop) {
      return res.status(400).json({ error: 'Missing shop parameter' });
    }
    
    const { session } = await getShopSession(shop);
    
    // Delete metafield
    const response = await fetch(
      `https://${shop}/admin/api/2024-07/metafields.json?namespace=ai_discovery&key=settings&owner_resource=shop`,
      {
        headers: {
          'X-Shopify-Access-Token': session.accessToken,
          'Content-Type': 'application/json'
        }
      }
    );
    
    if (response.ok) {
      const data = await response.json();
      const metafield = data.metafields?.[0];
      
      if (metafield) {
        await fetch(
          `https://${shop}/admin/api/2024-07/metafields/${metafield.id}.json`,
          {
            method: 'DELETE',
            headers: {
              'X-Shopify-Access-Token': session.accessToken
            }
          }
        );
      }
    }
    
    // Clear cache
    aiDiscoveryService.cache.clear();
    
    res.json({ success: true, message: 'Settings reset successfully' });
  } catch (error) {
    console.error('Failed to reset settings:', error);
    res.status(500).json({ error: error.message });
  }
});

/**
 * GET /api/ai-discovery/test-assets - Test endpoint to check theme assets
 */
router.get('/ai-discovery/test-assets', async (req, res) => {
  try {
    const shop = req.query.shop;
    const { session, accessToken } = await getShopSession(shop);
    
    // Get theme
    const themesResponse = await fetch(
      `https://${shop}/admin/api/2024-07/themes.json`,
      { headers: { 'X-Shopify-Access-Token': accessToken } }
    );
    
    const themesData = await themesResponse.json();
    const activeTheme = themesData.themes?.find(t => t.role === 'main');
    
    // List all assets
    const assetsResponse = await fetch(
      `https://${shop}/admin/api/2024-07/themes/${activeTheme.id}/assets.json`,
      { headers: { 'X-Shopify-Access-Token': accessToken } }
    );
    
    const assetsData = await assetsResponse.json();
    
    res.json({
      theme: activeTheme.name,
      totalAssets: assetsData.assets?.length,
      robotsFiles: assetsData.assets?.filter(a => a.key.includes('robots')),
      liquidFiles: assetsData.assets?.filter(a => a.key.endsWith('.liquid')).slice(0, 10)
    });
    
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

export default router;