# shopify.app.toml
# Public App Configuration for Shopify App Store Distribution

[application]
type = "public"
client_id = "2749a2f6d38ff5796ed256b5c9dc70a1"
name = "NEW AI SEO"
handle = "new-ai-seo"
application_url = "https://new-ai-seo-app-production.up.railway.app"
embedded = true

[webhooks]
api_version = "2025-07"

[auth]
redirect_urls = [
  "https://new-ai-seo-app-production.up.railway.app/auth/callback",
  "https://new-ai-seo-app-production.up.railway.app/api/auth/callback",
  "https://new-ai-seo-app-production.up.railway.app/api/auth"
]

[access_scopes]
scopes = "read_products,write_products,read_themes,write_themes,read_translations,write_translations,read_locales,read_metafields,write_metafields,read_metaobjects,write_metaobjects"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
# REMOVED: dev_store_url - not needed for public apps