# shopify.app.toml
# Public App Configuration for Shopify App Store Distribution

[application]
type = "public"
client_id = "2749a2f6d38ff5796ed256b5c9dc70a1"
name = "NEW AI SEO"
handle = "new-ai-seo"
application_url = "https://indexaize-aiseo-app-production.up.railway.app"
embedded = true

[webhooks]
api_version = "2025-07"

[auth]
redirect_urls = [
  "https://indexaize-aiseo-app-production.up.railway.app/auth/callback",
  "https://indexaize-aiseo-app-production.up.railway.app/api/auth/callback",
  "https://indexaize-aiseo-app-production.up.railway.app/api/auth",
  "https://indexaize-aiseo-app-production.up.railway.app/"
]

[access_scopes]
scopes = "read_products,write_products,read_themes,read_translations,write_translations,read_locales,read_metafields,write_metafields,read_metaobjects,write_metaobjects,read_markets"

# App Proxy Configuration for Sitemap
[app_proxy]
# This is the *destination* on your server that Shopify will call.
# You already mount your router there in server.js:
#   app.use('/apps/new-ai-seo', appProxyRouter)
url = "https://new-ai-seo-app-production.up.railway.app/apps"
url = "https://indexaize-aiseo-app-production.up.railway.app/apps"

# Merchant-facing URL on the storefront:
# https://{shop}.myshopify.com/apps/new-ai-seo/<anything>
subpath_prefix = "apps"
subpath = "new-ai-seo"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
# REMOVED: dev_store_url - not needed for public apps