# shopify.app.toml
client_id = "2749a2f6d38ff5796ed256b5c9dc70a1"
name = "NEW AI SEO"
handle = "new-ai-seo"
application_url = "https://new-ai-seo-app-production.up.railway.app"
embedded = true

[webhooks]
api_version = "2025-07"

[auth]
redirect_urls = ["https://new-ai-seo-app-production.up.railway.app/auth/callback"]

[access_scopes]
scopes = "read_products,write_products,read_themes,write_themes,read_translations,write_translations,read_locales,write_metafields,read_metafields,read_metaobjects,write_metaobjects,write_script_tags"

[pos]
embedded = false

[build]
include_config_on_deploy = true

