name = "AI SEO 2.0"
client_id = "2bc2b96aa1515eeda30ed377c41375d8"
application_url = "https://shopify-ai-seo-20-production.up.railway.app/"
embedded = true

[access_scopes]
scopes = "read_products,write_products,read_shopify_payments_payouts"
